version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: lol-postgres
    ports:
      - "6432:5432"
    volumes:
      - /tmp/postgres:/data/postgres
    env_file:
      - dev.docker.env
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: lol-pgadmin
    links:
      - postgres:postgres
    ports:
      - "9876:80"
    volumes:
      - /tmp/pgadmin:/root/.pgadmin
    env_file:
      - dev.docker.env
    networks:
      - postgres

  redis:
    image: "redis:alpine"
    container_name: lol-redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: lol-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
        - redis

networks:
  postgres:
    driver: bridge